<?php

namespace AppBundle\Entity;

/**
 * CylindreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CylindreeRepository extends \Doctrine\ORM\EntityRepository
{
}
