<?php

namespace AppBundle\Entity;

/**
 * PuissanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuissanceRepository extends \Doctrine\ORM\EntityRepository
{
}
