<?php

namespace AppBundle\Entity;

/**
 * Type_moteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_moteurRepository extends \Doctrine\ORM\EntityRepository
{
}
